Document: minipro
Title: Debian minipro Manual
Author: <insert document author here>
Abstract: This manual describes what minipro is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/minipro/minipro.sgml.gz

Format: postscript
Files: /usr/share/doc/minipro/minipro.ps.gz

Format: text
Files: /usr/share/doc/minipro/minipro.text.gz

Format: HTML
Index: /usr/share/doc/minipro/html/index.html
Files: /usr/share/doc/minipro/html/*.html
